### ISSUE TITLE
Radiograph classification chatbot not calling explainer

### ISSUE THREAD

**Issue by anneliret** [isee4xai/iSeeIssueTracker#10]
I've tested the invite link of the new Radiograph Classification - Public Test Use Case (cockpit-dev.isee4xai.com/invite/cc8578f6-bd94-401e-b747-e40e202d8a3e)
the case is published and complete. 
I've tested with one file uploaded (arm_fracture_not_treated), as a clinician. the model result is negative at 0.864 (which looks weird because the picture shows a fracture-results should be positive right ?)
then when selecting a question  for intent "transparency" (What features are used by the AI system?), the chatbot does not return any explanation. see picture 
![image](https://github.com/isee4xai/iSeeIssueTracker/assets/91963804/33a0f02f-ea74-4430-be02-3c13c3e14a22)
the transparency question is expected to call the integratedGradients and NearestNeighbours.

Chatbot directly asks for another question for the 2d intent (performance) and this 2d question works.

**Comment by anjanaw** [comment]
@anneliret  this is caused by a known issue which we are working on now. I have updated explanation strategy for Transparency as a workaround. Test and let me know if there are further issues.

**Comment by anjanaw** [comment]
Known issue
When there are more than one intent questions configured, and selecting a strategy from retrieval, the retrieved tree is not updated to point to all intent questions. 
work around
use "generate personalised strategy" and edit as needed.

**Comment by anneliret** [comment]
the gradients+nearestNeighbours strategy has worked. I will try the edit option too

**Comment by anneliret** [comment]
the manager persona works.

**Comment by anjanaw** [comment]
@anneliret I have done this already for this usecase
