### ISSUE TITLE
chatbot disconnected in the sensor anomaly detection case

### ISSUE THREAD

**Issue by anneliret** [isee4xai/iSeeIssueTracker#11]
the invite link for the sensor anomaly case give the error "chatbot disconnected".
https://cockpit-dev.isee4xai.com/invite/98a7bd4b-e7fc-4759-a09d-42c91a65f756
I've tried creating a new invite link as well as using the previous one.

**Comment by anjanaw** [comment]
can you provide a bit more detail like, does the JSON export works? and at which step does it get disconnected?

**Comment by anneliret** [comment]
one of the persona was no more complete (it was this morning). I have unselected and reselected a strategy and this has moved the persona as complete again. then the chatbot is back working.
