### ISSUE TITLE
BT structural validity

### ISSUE THREAD

**Issue by anjanaw** [isee4xai/iSeeIssueTracker#13]
@martcaro please check this scenario where user question has no siblings, 
<img width="903" alt="Screenshot 2024-02-24 at 21 34 37" src="https://github.com/isee4xai/iSeeIssueTracker/assets/233262/0de8e97c-69bc-4d67-ba4b-f5ad3c84fc8b">

**Comment by martcaro** [comment]
Anji, this is fixed, see the screenshot below. Please check if it is okay for you as well.
![image](https://github.com/isee4xai/iSeeIssueTracker/assets/18444486/15d15458-79de-48e8-95ef-266ca8fdbe28)
