### ISSUE TITLE
Chatbot disconnected before running an explainer

### ISSUE THREAD

**Issue by bfleisch** [isee4xai/iSeeIssueTracker#14]
Hello

Use case: 645e3b81cbf032384d5a550e 
Date/time: just tested now

I have the "chatbot disconnected" issue when running this use case. The sample data came correctly as well as the explanations strategy. But it fails to execute with the error message.

Thanks
Bruno

**Comment by anjanaw** [comment]
Was the usecase complete at the time it was tested? Right now it is not, see ML Engineer>Debugging 
<img width="769" alt="Screenshot 2024-03-03 at 16 47 32" src="https://github.com/isee4xai/iSeeIssueTracker/assets/233262/c52ed085-9d1e-45e6-8a50-810c4f8b9e85">
