### ISSUE TITLE
chatbot not loading after having edited the strategy in Telecom Notes case

### ISSUE THREAD

**Issue by anneliret** [isee4xai/iSeeIssueTracker#16]
we edited the LIME strategy in the BT editor, replace it by NLP Explainer, saved, then in the Cockpit we used "Test" and the chatbot directly said "disconnected"
![image](https://github.com/isee4xai/iSeeIssueTracker/assets/91963804/9e50da07-4c34-4959-91bc-66012cc7d8fa)
not even loading the "greet" message.

**Comment by anjanaw** [comment]
Try exporting the JSON on the cockpit before testing the chatbot. it seems to be incomplete and duplicate of #14

**Comment by anneliret** [comment]
yes, it has worked once complete and clicked on "retain" button.

**Comment by anjanaw** [comment]
@anneliret  please don't click retain if you are just testing if the case is complete. Retain is for when its ready to be saved on the case base.
