### ISSUE TITLE
telecom notes case: the NLP explainer work in cockpit validation but not in the chatbot

### ISSUE THREAD

**Issue by anneliret** [isee4xai/iSeeIssueTracker#17]
using "validate with explainer" in the cockpit, the NLP explainer returns and show results.
but when testing with the chatbot, there is an error when showing NLP explainer result or when calling it.

**Comment by anjanaw** [comment]
@bfleisch Please add output_description parameters to the explainer get function. See the comparison of NLP Classifier explainer and Text/LIME explainer in the screenshots. 
<img width="999" alt="Screenshot 2024-03-05 at 18 00 25" src="https://github.com/isee4xai/iSeeIssueTracker/assets/233262/23c31465-33d9-4bd9-b184-64ed88453bad">
<img width="999" alt="Screenshot 2024-03-05 at 18 00 33" src="https://github.com/isee4xai/iSeeIssueTracker/assets/233262/ebdb67ed-ee59-4649-97ee-223124087089">

**Comment by bfleisch** [comment]
hi @anjanaw  - thanks, it works ! 

I now have an issue with the formatting of the result. 

The explainer returns a HTML document but the chatbot does not seem to interpret it correctly.

Is there any guidelines for this ? Do we have other explainers that return formatted texts ?

Thanks a lot
best regards

Bruno

(@anneliret : FYI)

**Comment by bfleisch** [comment]
fixed.
