### ISSUE TITLE
chatbot disconnected error in Jiva use case

### ISSUE THREAD

**Issue by anneliret** [isee4xai/iSeeIssueTracker#2]
the Jiva use case (v99 now) has no explanation strategy selected anymore (so seen as incomplete I think). when starting the chatbot (as design user), I get this error "Chatbot is now disconnected. Please restart if you wish to start another session."

I have tried with invite link that I had created with V36 last week. and it does not go to v36, it uses directly v99... which does not work.

**Comment by anjanaw** [comment]
v99(now 101) has been updated and incompelete. 
test export JSON on the cockpit window and make sure the use case is complete before proceeding to the chatbot.
