### ISSUE TITLE
adding a free text evaluation question

### ISSUE THREAD

**Issue by anneliret** [isee4xai/iSeeIssueTracker#4]
I've added an extra question with free text answer to evaluation questions of Jiva/clinician/Transparency and Performance.
the Chatbot goes to it, but the "send" button is idle -I cannot send the text response.
![image](https://github.com/isee4xai/iSeeIssueTracker/assets/91963804/3f7073a9-2ea6-4efc-a5d1-0dbcc3dfb04f)

**Comment by anjanaw** [comment]
Fixed now. will be enabled after 1 character (earlier it was 100 words)
