### ISSUE TITLE
Rebuild Models (sklearn) image following an update on NLPClassifierExplainer 

### ISSUE THREAD

**Issue by bfleisch** [isee4xai/iSeeIssueTracker#5]
Hi

(to be assigned to Jesus - but he is not in the project members list?)

Could you please rebuild the iSee models (sklearn) image  as I've just rebuilt the NPLClassifierExplainer package (bug fix) ?

Thanks!
Bruno

**Comment by anjanaw** [comment]
@bfleisch I have added everyone now. Should be able to tag/assign people from now on.

**Comment by jesusdarias** [comment]
Just did. I can't seem to mark as closed though
