### ISSUE TITLE
Misc/AIModelPerformance Explainer Fails

### ISSUE THREAD

**Issue by K-Martin-RGULec** [isee4xai/iSeeIssueTracker#6]
When selecting the AI Model Performance explainer from the list of recommendations, it is 'red' to indicate not applicable. This causes two problems:

1) Model performance should always be applicable as a component of the explanation strategy, provided the information it needs (i.e. at least one performance metric) is present in the AI model section of the dashboard.
2) As this is currently the only Misc (and performance) explainer, it does not allow substitution in the BT editor, as no substitutes are found by either search strategy.

In combination, these two factors prevent the explainer from being attached to an explanation strategy, or replaced with anything similarly meaningful. The only current way to resolve this problem is to accept a different explainer, but no others exist for model performance.

**Comment by anjanaw** [comment]
Also need to address the applicability scenarios when the "AI Model Upload" section is not complete. 
In this case there will not be values for implementation framework, has training data and model access type, but still can calculate applicability mismatches for other features present like ai task, ai model and dataset type. 
this will affect both bt editor (not to complain about not having a model) and applicability logic and NL explanation generation.

**Comment by anjanaw** [comment]
assigning to @martcaro

**Comment by anjanaw** [comment]
updated iSeeCloodCBR 
1. ignore /Misc/AIModelPerformance Explainer from dataset type check.
2. skip properties from the AI model upload section when its not complete. 

@martcaro on the Explainer Library the dataset type for /Misc/AIModelPerformance is selected as Multivariate Tabular. Would it be useful to have an "Any" option here for expaliners that are applicable to any dataset type?

**Comment by anjanaw** [comment]
Adding a new dataset type for Misc Explainers planned for future and closing
