### ISSUE TITLE
Retrieve Explanation Strategies returns no data

### ISSUE THREAD

**Issue by jesusdarias** [isee4xai/iSeeIssueTracker#8]
I was creating [this use case](https://cockpit-dev.isee4xai.com/usecase/manage/65c889f2afebd5c40628eaf2) in the cockpit and I encountered an issue. When retrieving explanation strategies, nothing is returned. I imagine this is due to the lack of time series cases in the case base.

![image](https://github.com/isee4xai/iSeeIssueTracker/assets/71895708/5bf545bb-5214-4ec8-93c0-eab2c268ed5f)

 The expected behavior is that at least one strategy is returned even if it's not applicable. That way we can manually adapt it.

**Comment by anjanaw** [comment]
@ike01  lets add one case for each filter criteria.

**Comment by anjanaw** [comment]
@jesusdarias cases are added for all filter criteria. Please test and close.
